### ISSUE TITLE
Feedback Week 3

### ISSUE THREAD

**Issue by michaeldzjap** [IrisvanOllefen/project-tech#1]
# Feedback Assignments

- [x] job story
- [x] research bestaande dating apps / sites
- [x] designs (style guide, wireframes)
- [x] (statische) site voor je job story

## Job Story

Je job story is goed afgebakend. Hij is gedefinieerd vanuit het perspectief van de gebruiker en kan zowel een frontend als backend element bevatten. Hij kan misschien nog wel iets meer detail bevatten. Op welke manier wil je bijvoorbeeld hun favoriete boeken kunnen zien? Dus bv:

- _"When I have a new match, I want to receive a notification that contains their favourite books, So I can know what to talk about and see if we have a common interest."_
- _"When I like someone and we have a new match, I immediately want to be presented with an overview of their favourite books, So I can know what to talk about and see if we have a common interest."_
- _"When I have a new match, I want to see an overview of their favourite books when I visit their profile page, So I can know what to talk about and see if we have a common interest."_

## Research Dating Apps

Je dating app research ziet er netjes uit. Je hebt er aardig wat vergeleken op dezelfde punten, waardoor je een goed overzicht hebt gecreëerd van hoe de verschillende sites zich tot elkaar verhouden op die punten. Het is jammer dat je niet een afsluitende conclusie hebt toegevoegd, waarin je je belangrijkste bevindingen samen hebt gevat.

## Designs

Je style guide ziet er netjes uit en je wireframes maken vrij duidelijk hoe je je job story wilt visualiseren. Ik zou me wel beperken tot het favoriete boek overview deel en het overzicht van je matches. Ook nog eens een chat functionaliteit er bij maken lijkt me vrij ambitieus qua werk en heeft ook niet direct iets te maken met je gekozen job story.

## (Statische) site

De styling van je site is nog een beetje basic en de responsiveness en layout van de verschillende views kan ook nog wel iets beter uitgewerkt worden. Dat is allemaal nu nog een beetje minimaal. Het sluit wel allemaal goed aan bij je job story, met uitzondering van de chat pagina dus. Ik zou die dus eigenlijk voor nu maar even achterwege laten en me focussen op het stylen en de gebruikerservaring van de andere 2 pagina's. Daar heb je nu nog best wel wat werk aan. Daar is ook nog wel de tijd voor nu, dus gebruik dat in je voordeel.

**Comment by IrisvanOllefen** [comment]
Goede feedback Michael, bedankt! Hier kan ik zeker iets mee doen!
